<?php

namespace minervis\Litello\Utils;

use minervis\Litello\Repository;

/**
 * Trait LitelloTrait
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @package minervis\Litello\Utils
 *
 * @author Minervis GmbH <jephte.abijuru@minervis.com>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
trait LitelloTrait
{

    /**
     * @return Repository
     */
    protected static function litello() : Repository
    {
        return Repository::getInstance();
    }
}
